default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "bizzrail_card_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "bizzrail_card_test" } %>

production:
  primary: &primary_production
    <<: *default
    database: bizzrail_card_production
    username: bizzrail_card
    password: <%= ENV["BIZZRAIL_CARD_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: bizzrail_card_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: bizzrail_card_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: bizzrail_card_production_cable
    migrations_paths: db/cable_migrate
